### ISSUE TITLE
Linux: Failed to load GDK

### ISSUE THREAD

**Issue by duncanam** [adxsoft/TeelineMate#1]
I installed and placed in /usr/local and ran it, resulting in:

`Failed to load library 'gdk' (tried libgdk-x11-2.0.so.0)`

I checked my packages and have some sort of Glib installed as well as various GTK/GDK libraries. Is there something else I should be installing in addition that I'm missing? For the time being I have the windows version functioning in Wine. 

Thanks.

**Comment by adxsoft** [comment]
Hi
Thanks for the feedback. TeelineMate is a Livecode app which is converted to a linux executable and unfortunately I cannot resolve the issue. If you download Livecode community Edition on Linux and then load the teelinemate livecode file (the source code) you should be able to do File, Save as Standalone program. This will create a livecode executable that runs on your system.
Hopeyfully this will resolve the issue for you
